services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/menucraft_frontend:latest
    container_name: menucraft_frontend
    restart: always
    environment:
      - TZ=Europe/Sofia
    networks:
      - web

  backend:
    image: ${DOCKERHUB_USERNAME}/menucraft_backend:latest
    container_name: menucraft_backend
    restart: always
    env_file: .env
    volumes:
      - /home/ubuntu/menucraft/backend_logs:/app/logs
    environment:
      - TZ=Europe/Sofia
      - JAVA_OPTS=-Duser.timezone=Europe/Sofia
      - ELASTIC_APM_SERVICE_NAME=MenuCraft
      - ELASTIC_APM_ENVIRONMENT=production
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL}
      - ELASTIC_APM_API_KEY=${ELASTIC_APM_API_KEY}
      - ELASTIC_APM_APPLICATION_PACKAGES=bg.menucraft
      - ELASTIC_APM_LOG_SENDING=true
      - ELASTIC_APM_LOG_ECS_REFORMATTING=OVERRIDE
    networks:
      - web

networks:
  web:
    external: true
