spring:
  profiles:
    active: dev

  application:
    name: MenuCraft

  jackson:
    time-zone: Europe/Sofia

  datasource:
    url: ${DB_URL_MENU_CRAFT}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  threads:
    virtual:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
        jdbc:
          time_zone: Europe/Sofia
jwt:
  secret-key: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

facebook:
  app-id: ${FACEBOOK_APP_ID}
  app-secret: ${FACEBOOK_APP_SECRET}
  redirect-uri: ${FACEBOOK_REDIRECT_URI}
  graph-api-base: ${GRAPH_API_URL}

encryption:
  aes-secret: ${AES_ENCRYPTION_SECRET}

app:
  frontend-url: http://localhost:5173

server:
  port: 8090

# ============================================================
# DEV PROFILE
# ============================================================
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    hikari:
      pool-name: MenuCraftPool
      maximum-pool-size: 12
      minimum-idle: 4
      connection-timeout: 10000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: false
      validation-timeout: 3000
      leak-detection-threshold: 20000

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: WARN

# ============================================================
# PROD PROFILE
# ============================================================
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    hikari:
      pool-name: MenuCraftPool
      maximum-pool-size: 4
      minimum-idle: 2
      connection-timeout: 8000
      idle-timeout: 300000
      max-lifetime: 1700000
      keepalive-time: 300000
      auto-commit: false
      validation-timeout: 3000
      leak-detection-threshold: 15000

app:
  frontend-url: https://menucraft.online

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
