filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/menucraft/menucraft.json
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true
    json.expand_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "menucraft-logs-%{+yyyy.MM.dd}"

setup.template.name: "menucraft-logs"
setup.template.pattern: "menucraft-logs-*"
setup.ilm.enabled: false

setup.kibana:
  host: "kibana:5601"

logging.level: info
logging.to_files: false
